##### port #####
server:
  port: 8888

spring:
   cloud:
    config:
      server:
        git:
          uri: ${GITHUB_CONFIG_PATH}
          default-label: main
          username : ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN_KEY}
