spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: service-auth-app

management:
  tracing:
    sampling:
      probability: 1