##### port #####
server:
  port: 9090

##### data postgresql #####
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    service:
      name: service-auth
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/${Auth_DB_DB_NAME}   # PostgreSQL veritabanı URL'si
    username: ${DB_USERNAME}                                    # Veritabanı kullanıcı adı
    password: ${DB_PASSWORD}                                 # Veritabanı şifresi
    driver-class-name: ${DB_DRIVER}           # PostgreSQL JDBC sürücüsü
  jpa:
    hibernate:
      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
    show-sql: true

##### swagger-ui path #####
springdoc:
  swagger-ui:
    path: /swagger-ui.html