##### port #####
server:
  port: 80

spring:
  cloud:
    gateway:
      default-filters:
        - RewritePath=/(?<segment>.*),/$\{segment}
      routes:
          - id: service-auth
            uri: http://localhost:9090
            predicates:
              - Path=/auth/**
          - id: service-user-profile
            uri: http://localhost:9091
            predicates:
              - Path=/user/**
          - id: service-agent
            uri: http://localhost:9092
            predicates:
              - Path=/agent/**
          - id: service-buyer
            uri: http://localhost:9093
            predicates:
              - Path=/buyer/**
          - id: service-properties
            uri: http://localhost:9094
            predicates:
              - Path=/properties/**


